#ifndef CANDY_DATA__H
#define CANDY_DATA__H

#include "cocos-ext.h"
#include "../CommonMacro.h"

#define CANDY_USE_PLIST
#ifdef WIN32
//#define CLOSE_ARMATURE
#endif
#define CANDY_MAP_WIDTH	9
#define CANDY_MAP_HEIGH 	9


#define CANDY_CELL_WIDTH		76
#define CANDY_CELL_HEIGHT		76


#define BG_GRID_TAG			1201


#define TAG_ACTION_DISPEL_TIPS			101
#define TAG_ACTION_FADE_TIPS			102
#define TAG_ACTION_UPSPRING			103

#define BG_GRID_ORDER			1


// 障碍物 糖果 层级
#define BARRIER_BOTTOM_ORDER 	9
#define CLIPPER_ORDER			10		//candy in clipper
#define BARRIER_TOP_ORDER		11

#define NEW_PORTAL_ORDER		6

#define SCORE_ORDER				12
#define INGREDIENT_ORDER		15

#define DISPEL_EFFECT_ORDER		12
#define PORTAL_ORDER			12

#define CANDY_LAYER_ORDER		-1
#define UI_LAYER_ORDER			2
#define EFFECT_LAYER_ORDER		2
#define GUIDE_LAYER_ORDER		3
#define RESULT_LAYER_ORDER		4

// 糖果得分
#define CANDY_SCORE_BASE				50
#define CANDY_SCORE_BARRIER			50
#define CANDY_SCORE_SINGLE_DISPEL		80
#define CANDY_SCORE_BOMB				500
#define CANDY_SCORE_LOCK				0
#define CANDY_SCORE_CREAM1			20
#define CANDY_SCORE_CREAM2			20
#define CANDY_SCORE_CREAM3			20
#define CANDY_SCORE_JELLY				1000
#define CANDY_SCORE_INGREDIENT			12000
#define CANDY_SCORE_CHOCOLATE			200
#define CANDY_SCORE_EXPLOSION			3000
#define CANDY_SCORE_USE_STEPS			3000

// 按键优先级
#define GUIDE_SKIP_PRIORITY				-256
#define GUIDE_LAYER_PRIORITY			-127
#define CANDY_LAYER_PRIORITY			0
#define UI_LAYER_PRIORITY				-1
#define RESULT_LAYER_PRIORITY			-256
#define RESULT_WIDGET_PRIORITY			-257

#define COLLECT_MAX_TYPE_NUM  3


#define HSL_TIPS_H			0
#define HSL_TIPS_S			0.9f
#define HSL_TIPS_L			0.15f

typedef struct
{
	int x;
	int y;
}CandyIndex;


//糖果颜色
typedef enum
{
	CANDY_COLOR_RED,
	CANDY_COLOR_BLUE,
	CANDY_COLOR_GREEN,
	CANDY_COLOR_YELLOW,
	CANDY_COLOR_ORANGE,
	CANDY_COLOR_PURPLE,
	CANDY_COLOR_NORMAL_NUM,
	CANDY_COLOR_SPECIAL,//彩球
	CANDY_COLOR_BOMBING,//触发炸弹时，不与同颜色消除
	CANDY_COLOR_CHERRY,	//掉落物品 樱桃
	CANDY_COLOR_CHESNUT, //掉落物品 板栗
	CANDY_COLOR_LICORICE,//甘草
	CANDY_COLOR_NUM,
}CandyColor;

//糖果种类
typedef enum
{
	CANDY_SPECIAL_NORMAL,
	CANDY_SPECIAL_HORIZONTAL,
	CANDY_SPECIAL_VERTICAL,
	CANDY_SPECIAL_BOMB,
	CANDY_SPECIAL_BOMBING,
	CANDY_SPECIAL_COLORFULL,	//彩球
	CANDY_SPECIAL_EXPLOSION,	//定时炸弹
	CANDY_SPECIAL_INGREDIENT,	//苹果 樱桃 等
	CANDY_SPECIAL_LICORICE,		//甘草
	CANDY_SPECIAL_NUM
}CandySpecial;

//组合效果
typedef enum
{
	CANDY_COM_COLORFULL_COLORFULL,
	CANDY_COM_COLORFULL_NORMAL,
	CANDY_COM_COLORFULL_STRIPE,
	CANDY_COM_COLORFULL_BOMB,
	CANDY_COM_STRIPE_STRIPE,
	CANDY_COM_STRIPE_BOMB,
	CANDY_COM_BOMB_BOMB,
	CANDY_COM_NUM,
}CandyComType;

//收集模式 种类
typedef enum
{
	CANDY_COLLECT_RED,
	CANDY_COLLECT_BLUE,
	CANDY_COLLECT_GREEN,
	CANDY_COLLECT_YELLOW,
	CANDY_COLLECT_ORANGE,
	CANDY_COLLECT_PURPLE,
	CANDY_COLLECT_STRIPE,
	CANDY_COLLECT_BOMB,
	CANDY_COLLECT_COLORFULL,
	CANDY_COLLECT_STR_STR,
	CANDY_COLLECT_STR_BOMB,
	CANDY_COLLECT_STR_COLOR,
	CANDY_COLLECT_BOMB_BOMB,
	CANDY_COLLECT_BOMB_COLOR,
	CANDY_COLLECT_COLOR_COLOR,
	CANDY_COLLECT_NUM
}CandyCollectType;

inline CandyIndex cIndex(int x, int y)
{
	CandyIndex ret;
	ret.x = x;
	ret.y = y;
	return ret;
}

#endif
