#ifndef CANDY_MUSIC__H
#define CANDY_MUSIC__H

#include "cocos2d.h"
#include "CandyCommon.h"

USING_NS_CC;

typedef enum
{
	CANDY_EFFECT_COMBO1,
	CANDY_EFFECT_COMBO2,
	CANDY_EFFECT_COMBO3,
	CANDY_EFFECT_COMBO4,
	CANDY_EFFECT_COMBO5,
	CANDY_EFFECT_COMBO6,
	CANDY_EFFECT_COMBO7,
	CANDY_EFFECT_COMBO8,
	CANDY_EFFECT_COMBO9,
	CANDY_EFFECT_COMBO10,
	CANDY_EFFECT_COMBO11,
	CANDY_EFFECT_COMBO12,
	CANDY_EFFECT_PRAISE2,
	CANDY_EFFECT_PRAISE3,
	CANDY_EFFECT_PRAISE4,
	CANDY_EFFECT_PRAISE5,
	CANDY_EFFECT_PRAISE6,
	CANDY_EFFECT_PRAISE7,
	CANDY_EFFECT_DROP1,
	CANDY_EFFECT_DROP2,
	CANDY_EFFECT_DROP3,
	CANDY_EFFECT_DROP4,
	CANDY_EFFECT_BUTTON,
	CANDY_EFFECT_CHANGE_FAIL,
	CANDY_EFFECT_CHANGE_DONE,
	CANDY_EFFECT_CHANGE_LICORICE,
	CANDY_EFFECT_NEW_VERTICAL,
	CANDY_EFFECT_NEW_HORIZON,
	CANDY_EFFECT_NEW_BOMB,
	CANDY_EFFECT_NEW_COLORFULL,
	CANDY_EFFECT_COM_COLOR_COLOR,
	CANDY_EFFECT_COM_COLOR_BOMB,
	CANDY_EFFECT_COM_COLOR_STRIPE,
	CANDY_EFFECT_COM_COLOR_NORMAL,
	CANDY_EFFECT_COM_BOMB_BOMB,
	CANDY_EFFECT_COM_BOMB_STRIPE,
	CANDY_EFFECT_DISPEL_STRIPE,
	CANDY_EFFECT_DISPEL_BOMB,
	CANDY_EFFECT_NO_ENOUGH_STEPS,
	CANDY_EFFECT_STAGE_CLEAR,
	CANDY_EFFECT_GAME_WARNING,
	CANDY_EFFECT_TIME_ALARM,
	CANDY_EFFECT_ROULETTE_IN,
	CANDY_EFFECT_CLEAR_STAR,
	CANDY_EFFECT_CLEAR_TIPS,
	CANDY_EFFECT_FAILED_TIPS,
	CANDY_EFFECT_RESORT_TIPS,
	CANDY_EFFECT_INGREDIENT,
	CANDY_EFFECT_USE_STEP1,
	CANDY_EFFECT_USE_STEP2,
	CANDY_EFFECT_USE_STEP3,
	CANDY_EFFECT_USE_STEP4,
	CANDY_EFFECT_USE_STEP5,
	CANDY_EFFECT_CHEER,
	CANDY_EFFECT_CANDYCRUSH,
	CANDY_EFFECT_HAMMER,
	CANDY_BG_BGM1,
	CANDY_BG_BGM2,
	CANDY_BG_BGM3,
	CANDY_BG_BGM4,
	CANDY_BG_ROULETTE,
	CANDY_BG_GAME_CLEAR,
	CANDY_BG_GAME_OVER,
	CANDY_MUSIC_NUM,
}CandyMusicType;

class CandyMusic
{
	public:
		CandyMusic(); 
		~CandyMusic();

	public:
		void updateCandyMusic(void);
		
	public:
		void reloadCandyGameMusic(void);
		void unreloadCandyGameMusic(void);
		
	public:
		void playMusic(CandyMusicType type);
		void playComboEffect(int comboNumber);
		void playUseStepEffect(int num);
		void playPraiseEffect(int comboNumber);
		void playDropEffect(int dropLen);
		void playBgm(void);
	private:
		void initMusicPath(void);
	
	private:
		char* candyMusicPath[CANDY_MUSIC_NUM];
		int playingEffect[CANDY_MUSIC_NUM];
		int warningEffectId;
};

#endif