/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_weme_candy_util_CandyPay */

#ifndef _Included_org_weme_candy_util_CandyPay
#define _Included_org_weme_candy_util_CandyPay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_weme_candy_util_CandyPay
 * Method:    PaySuccess
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_weme_candy_util_CandyPay_PaySuccess
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_weme_candy_util_CandyPay
 * Method:    PayFailed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_weme_candy_util_CandyPay_PayFailed
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
